server:
  port: 8080

spring:
  application:
    name: blogvista-backend
  datasource:
    url: jdbc:mysql://localhost:3306/blogvista
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

google:
  clientId: 645561507231-9h880rl8j5aske5c52c49epfjgukp034.apps.googleusercontent.com
